name: deploy
on:
  push:
    branches:
      - main

env:
  TF_VAR_cloudflare_account_id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
  AWS_ENDPOINT_URL_S3: https://${{ secrets.CLOUDFLARE_ACCOUNT_ID }}.r2.cloudflarestorage.com
  NODE_VERSION: 22
  PNPM_VERSION: 10

jobs:
  apply_terraform:
    name: Apply terraform environment
    runs-on: ubuntu-latest

    steps:
      - uses: hashicorp/setup-terraform@v3

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Init terraform environment
        run: terraform init

      - name: Apply changes
        run: terraform apply -auto-approve

  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    needs: [apply_terraform]

    steps:
      - uses: hashicorp/setup-terraform@v3

      - name: Checkout code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"

      - name: Init terraform environment
        run: terraform init

      - name: Install dependencies
        run: pnpm install

      # ここでterraformのoutputを拾ってきてenvを出力してもよいかも
      # 現時点ではoutputはないので関係ない

      - name: Deploy workers
        run: pnpm run deploy
